# Generated by Django 5.1.2 on 2024-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.SmallIntegerField(verbose_name='ID')),
                ('device_status', models.BooleanField(verbose_name='Status')),
                ('city', models.CharField(max_length=20, verbose_name='Cidade')),
                ('zone', models.CharField(max_length=20, verbose_name='Zona')),
                ('address', models.CharField(max_length=20, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=6, verbose_name='Número')),
                ('complemento', models.CharField(max_length=250, verbose_name='Complemento')),
                ('zip_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('travel_time', models.TimeField(verbose_name='Tempo de deslocamento')),
                ('observacoes', models.CharField(max_length=250, verbose_name='Obs')),
            ],
        ),
    ]
